#+TITLE: A (Pr)operad of (Pr)operad Algebras
#+AUTHOR: Matt Alexander
#+DATE: June 6, 2026
#+EMAIL: mpa097@uregina.ca
#+OPTIONS: H:1 toc:nil
#+LATEX_CLASS: beamer
#+LATEX_CLASS_OPTIONS: [presentation]
#+LaTeX_HEADER: \makeatletter\def\input@path{{./}{./shared/}{./shared/themes/}}\makeatother
#+LaTeX_HEADER: \usepackage{beamerthemequeer}
#+LaTeX_HEADER: \usepackage{shared-preamble}




* Main Results


\begin{proposition}{The Operad of Operad Algebras}{operad-of-operad-alg-gen}
Let $\mathcal{V}$ be a symmetric monoidal category with all small coproducts such that the monoidal product distributes over all \emph{finite} coproducts, and let $\mathcal{O}$ be a coloured operad in $\mathcal{V}$. Then for any small category, $\mathcal{C}$, there exists an operad $\mathcal{O}^{\mathcal{C}}$ in $\mathcal{V}$ whose algebras are the functors 
\begin{equation*}
F: \mathcal{C} \to \mathcal{O} \text{-Alg}.
\end{equation*}
\end{proposition}

* Main Results (Properad Version)

\begin{proposition}{Properad of Properad Algebras}{prop-of-prop-algs}
Let $\mathcal{P}$ be a coloured properad in a closed monoidal category with all small coproducts $\mathcal{V}$, where the monodial product distributes over all \emph{finite} coproducts. For any small category $\mathcal{C}$, there exists a properad $\mathcal{P}^{\mathcal{C}}$ whose algebras are the functors
\begin{equation*}
F: \mathcal{C} \to \mathcal{P}\text{-Alg}.
\end{equation*}
\end{proposition}

* Generators and Relations

\newthought{Between objects in $\mathcal{C}$: }
\[
\mathcal{O}^{\mathcal{C}}_{\text{gen}}[A_{\alpha} \mid B_{\alpha}] = \bigsqcup_{f: A \to B} I
\]
when $A \ne B$.

\newthought{Copies of $\mathcal{O}^{\mathcal{C}}$: }
\[
\mathcal{O}^{\mathcal{C}}_{\text{gen}}[A_{\alpha_{1}} \ldots A_{\alpha_{n}} \mid A_{\beta}] = \mathcal{O}[\alpha_{1} \ldots \alpha_{n}]
\]
=Endomorphisms:= 
\[
\mathcal{O}^{\mathcal{C}}_{\text{gen}}[A_{\alpha} \mid A_{\alpha}] = \mathcal{O}[\alpha \mid \alpha] \sqcup \bigsqcup_{f: A \to A} I
\]


* Explicit Form (infinitary distributivity)

In the case that $\otimes$ distributes over /all small coproducts/
\[
\mathcal{O}^{\mathcal{C}}[\bar{A}_{\bar{\alpha}} \mid B_{\beta}] = \coprod_{f^i: A^i \to B} \mathcal{O}[\bar{\alpha} \mid \beta]
\]

* Precursors

** /Coloured Operads/, Yau (2017)

- The construction of $\mathcal{O}^{\mathcal{C}}$ is left as an exercise.

\bigskip

** /Operads for algebraic quantum field theory/, Benini, Schenkel, Woike (2021)


- $\mathcal{O}^{\mathcal{C}}$ is constructed in the case that $\mathcal{O}$ is the associative operad:
\[
\operatorname{Assoc}^{\mathcal{C}}
\]


* Orthogonal Categories

** Definition

Let $\mathcal{C}$ be a small category. An /orthogonality relation/ $\perp$ on $\mathcal{C}$ is a relation on pairs of morphisms in $\mathcal{C}$ such that if $f \perp g$
then $f$ and $g$ have the /same codomain/, and are required to satisfy

- If $f \perp g$ then $g \perp f$.

- If $g \perp h$ then $fg \perp fh$ for all composable $f$.

- If $g_1 \perp g_2$ then $g_1 h \perp g_2 k$ for all composable $h,k$.

\bigskip 
An /orthogonal category/ is a small category $\mathcal{C}$ with an orthogonality relation $\perp$.

=Intuition:= $f \perp g$ means that the regions corresponding to $f$ and $g$ are /causally disjoint/

* Causality

In order to be a physical theory, an AQFT must satisfy the /causality condition/:

\begin{center}
\begin{tikzcd}[ampersand replacement=\&]
F(A) \otimes F(B) \arrow[r, "F(f) \otimes F(g)"] \arrow[d, swap, "F(f) \otimes F(g)"] \& F(C) \otimes F(C) \arrow[r, "\tau"] \& F(C) \otimes F(C) \arrow[d, "\mu"] \\
F(C) \otimes F(C) \arrow[rr, swap, "\mu"]  \& \& F(C)
\end{tikzcd}
\end{center}

\bigskip

whenever $f \perp g$.



* Introducing Homotopy

- Homotopy allows us to capture gauge theories
- Most common approaches: bar-cobar (ex. chain complexes), W-construction

\bigskip

** Homotopy Quantum Field Theory, Yau (2019)


- Wraps the entire QFT in homotopy:
\[
W(\operatorname{Assoc}^{\mathcal{C}})
\]


* Pointwise A_{\infty}-algebras

Picking out a monoid at any point in the category $\mathcal{C}$
\[
\operatorname{Assoc} \to \mathcal{O}^{\mathcal{C}}
\]
induces an adjunction
\[
\operatorname{Alg}(\operatorname{Assoc}_{\infty}) \rightleftarrows \operatorname{Alg}(W(\mathcal{\operatorname{Assoc}}^{\mathcal{C}})),
\]
which picks out the corresponding $A_{\infty}$-algebra at that object.

* Pointwise A_{\infty}-algebras 

Using the $\mathcal{O}^{\mathcal{C}}$ construction, we can create a model for AQFTs of the form
\[
\operatorname{Assoc}_{\infty}^{{\mathcal{C}}}.
\]
This gives us finer control over the homotopy /in the algebras/.

\bigskip

** Properads

Structures like Hopf algebras, L_{\infty}-bialgebras, and quantum groups are /properadic/.
- We can take our properadic construction and then inject homotopy through
       - Vallette's Properadic Koszul Duality
       - Kontsevich's Graph Complexes

* Hopf-Laplace Algebras

A /Hopf algebra/ is a unital associative $k$-algebra, $H$, with maps 

\medskip

- \fbox{Comultiplication: } $\Delta: H \to H \otimes H$

- \fbox{Counit: } $\varepsilon: H \to k$

- \fbox{Antipode: } An involution $S: H \to H$

\bigskip

satisfying the appropriate compatibility conditions between the algebraic and coalgebraic structure.

A /Laplace pairing/ on a Hopf algebra is a bilinear form $\gen{\cdot, \cdot}: H \otimes H \to k$ satisfying

\[
\gen{x, yz} = \sum \gen{x_{(1)}, y} \gen{x_{(2)}, z}
\]
\[
\gen{xy, z} = \sum \gen{x, z_{(1)}} \gen{y, z_{(2)}}
\]
\[
\gen{1, x} = \gen{x, 1} = \varepsilon(1)
\]

=Intuition:= Laplace pairings behave like /correlation functions/ from quantum field theory!

* Properad of Laplace Hopf AQFTs

Let $(\mathcal{C}, \perp)$ be an orthogonal category. A /Laplace Hopf algebraic quantum field theory/ is a functor
\begin{align*}
F: \mathcal{C} \to \mathcal{LB}(\mathcal{V})
\end{align*}
where $\mathcal{LB}(\mathcal{V})$ is the category of Laplace bialgebras on a symmetric monoidal category $\mathcal{V}$, such that the following \textbf{causality diagram} commutes:

\begin{center}
\begin{tikzcd}[column sep = 3cm, ampersand replacement=\&]
F(A)^{\otimes m} \otimes F(B)^{\otimes n} \ar[r, "F(f)^{\otimes m} \otimes F(g)^{\otimes n}"] \ar[d, swap, "\gen{-,-}_m \otimes \gen{-,-}_n"] \& F(C)^{\otimes m} \otimes F(C)^{\otimes n} \ar[d, "\gen{-,-}_{m + n}"] \\
k \otimes k \ar[r, swap, "\mu_k"]  \& k 
\end{tikzcd}
\end{center}
commutes whenever $f: A \to C$ and $g: B \to C$ satisfy $f \perp g$, where $\gen{-,-}_{m+n}$ is the (m+n)-arity correlation function on $F(C)$.



